language: julia
os:
  - linux
julia:
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
- name: Julia TagBot
  uses: JuliaRegistries/TagBot@v1.8.1
env:
   - PYTHON=""
after_success:
- julia -e 'using Pkg;
            Pkg.add("Coverage");
            using Coverage;
            Codecov.submit(Codecov.process_folder())'
